name: 部署 GitHub Pages

on:
  push:
    branches: [main]  # 触发分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'  # 缓存 yarn 依赖

      - name: Install Dependencies
        run: yarn --frozen-lockfile  # 确保 lockfile 一致

      - name: Build
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # 构建输出目录
          # 如果不需要推送到其他仓库，移除 `repository` 参数